import { Component } from '@angular/core';
import { Pokemon } from '../../model/pokemon.model';
import { PokemonItemComponent } from '../pokemon-item/pokemon-item.component';

@Component({
  selector: 'app-pokemon-list',
  standalone: true,
  imports: [PokemonItemComponent],
  templateUrl: './pokemon-list.component.html',
  styleUrl: './pokemon-list.component.css'
})
export class PokemonListComponent {

onclick(pokemon: Pokemon) {
  this.selectedPokemon = pokemon;
}

ngOnInit(): void {
  this.selectedPokemon = this.pokemons[0];
}

  selectedPokemon! : Pokemon;

  pokemons: Pokemon[] = [
    { id: 1, name: "Bulbasaur", type: "grass", icon: "1.png" },
    { id: 2, name: "Ivysaur", type: "grass", icon: "2.png" },
    { id: 3, name: "Venusaur", type: "grass", icon: "3.png" },
    { id: 4, name: "Charmander", type: "fire", icon: "4.png" },
    { id: 5, name: "Charmeleon", type: "fire", icon: "5.png" },
    { id: 6, name: "Charizard", type: "fire", icon: "6.png" },
    { id: 7, name: "Squirtle", type: "water", icon: "7.png" },
    { id: 8, name: "Wartortle", type: "water", icon: "8.png" },
    { id: 9, name: "Blastoise", type: "water", icon: "9.png" },
    { id: 10, name: "Caterpie", type: "bug", icon: "10.png" },
    { id: 11, name: "Metapod", type: "bug", icon: "11.png" },
    { id: 12, name: "Butterfree", type: "bug", icon: "12.png" },
    { id: 13, name: "Weedle", type: "bug", icon: "13.png" },
    { id: 14, name: "Kakuna", type: "bug", icon: "14.png" },
    { id: 15, name: "Beedrill", type: "bug", icon: "15.png" },
    { id: 16, name: "Pidgey", type: "normal", icon: "16.png" },
    { id: 17, name: "Pidgeotto", type: "normal", icon: "17.png" },
    { id: 18, name: "Pidgeot", type: "normal", icon: "18.png" },
    { id: 19, name: "Rattata", type: "normal", icon: "19.png" },
    { id: 20, name: "Raticate", type: "normal", icon: "20.png" },
    { id: 21, name: "Spearow", type: "normal", icon: "21.png" },
    { id: 22, name: "Fearow", type: "normal", icon: "22.png" },
    { id: 23, name: "Ekans", type: "poison", icon: "23.png" },
    { id: 24, name: "Arbok", type: "poison", icon: "24.png" },
    { id: 25, name: "Pikachu", type: "electric", icon: "25.png" },
    { id: 26, name: "Raichu", type: "electric", icon: "26.png" },
    { id: 27, name: "Sandshrew", type: "ground", icon: "27.png" },
    { id: 28, name: "Sandslash", type: "ground", icon: "28.png" },
    { id: 29, name: "Nidoran♀", type: "poison", icon: "29.png" },
    { id: 30, name: "Nidorina", type: "poison", icon: "30.png" },
    { id: 31, name: "Nidoqueen", type: "poison", icon: "31.png" },
    { id: 32, name: "Nidoran♂", type: "poison", icon: "32.png" },
    { id: 33, name: "Nidorino", type: "poison", icon: "33.png" },
    { id: 34, name: "Nidoking", type: "poison", icon: "34.png" },
    { id: 35, name: "Clefairy", type: "fairy", icon: "35.png" },
    { id: 36, name: "Clefable", type: "fairy", icon: "36.png" },
    { id: 37, name: "Vulpix", type: "fire", icon: "37.png" },
    { id: 38, name: "Ninetales", type: "fire", icon: "38.png" },
    { id: 39, name: "Jigglypuff", type: "normal", icon: "39.png" },
    { id: 40, name: "Wigglytuff", type: "normal", icon: "40.png" },
    { id: 41, name: "Zubat", type: "poison", icon: "41.png" },
    { id: 42, name: "Golbat", type: "poison", icon: "42.png" },
    { id: 43, name: "Oddish", type: "grass", icon: "43.png" },
    { id: 44, name: "Gloom", type: "grass", icon: "44.png" },
    { id: 45, name: "Vileplume", type: "grass", icon: "45.png" },
    { id: 46, name: "Paras", type: "bug", icon: "46.png" },
    { id: 47, name: "Parasect", type: "bug", icon: "47.png" },
    { id: 48, name: "Venonat", type: "bug", icon: "48.png" },
    { id: 49, name: "Venomoth", type: "bug", icon: "49.png" },
    { id: 50, name: "Diglett", type: "ground", icon: "50.png" },
    { id: 51, name: "Dugtrio", type: "ground", icon: "51.png" },
    { id: 52, name: "Meowth", type: "normal", icon: "52.png" },
    { id: 53, name: "Persian", type: "normal", icon: "53.png" },
    { id: 54, name: "Psyduck", type: "water", icon: "54.png" },
    { id: 55, name: "Golduck", type: "water", icon: "55.png" },
    { id: 56, name: "Mankey", type: "fighting", icon: "56.png" },
    { id: 57, name: "Primeape", type: "fighting", icon: "57.png" },
    { id: 58, name: "Growlithe", type: "fire", icon: "58.png" },
    { id: 59, name: "Arcanine", type: "fire", icon: "59.png" },
    { id: 60, name: "Poliwag", type: "water", icon: "60.png" },
    { id: 61, name: "Poliwhirl", type: "water", icon: "61.png" },
    { id: 62, name: "Poliwrath", type: "water", icon: "62.png" },
    { id: 63, name: "Abra", type: "psychic", icon: "63.png" },
    { id: 64, name: "Kadabra", type: "psychic", icon: "64.png" },
    { id: 65, name: "Alakazam", type: "psychic", icon: "65.png" },
    { id: 66, name: "Machop", type: "fighting", icon: "66.png" },
    { id: 67, name: "Machoke", type: "fighting", icon: "67.png" },
    { id: 68, name: "Machamp", type: "fighting", icon: "68.png" },
    { id: 69, name: "Bellsprout", type: "grass", icon: "69.png" },
    { id: 70, name: "Weepinbell", type: "grass", icon: "70.png" },
    { id: 71, name: "Victreebel", type: "grass", icon: "71.png" },
    { id: 72, name: "Tentacool", type: "water", icon: "72.png" },
    { id: 73, name: "Tentacruel", type: "water", icon: "73.png" },
    { id: 74, name: "Geodude", type: "rock", icon: "74.png" },
    { id: 75, name: "Graveler", type: "rock", icon: "75.png" },
    { id: 76, name: "Golem", type: "rock", icon: "76.png" },
    { id: 77, name: "Ponyta", type: "fire", icon: "77.png" },
    { id: 78, name: "Rapidash", type: "fire", icon: "78.png" },
    { id: 79, name: "Slowpoke", type: "water", icon: "79.png" },
    { id: 80, name: "Slowbro", type: "water", icon: "80.png" },
    { id: 81, name: "Magnemite", type: "electric", icon: "81.png" },
    { id: 82, name: "Magneton", type: "electric", icon: "82.png" },
    { id: 83, name: "Farfetch'd", type: "normal", icon: "83.png" },
    { id: 84, name: "Doduo", type: "normal", icon: "84.png" },
    { id: 85, name: "Dodrio", type: "normal", icon: "85.png" },
    { id: 86, name: "Seel", type: "water", icon: "86.png" },
    { id: 87, name: "Dewgong", type: "water", icon: "87.png" },
    { id: 88, name: "Grimer", type: "poison", icon: "88.png" },
    { id: 89, name: "Muk", type: "poison", icon: "89.png" },
    { id: 90, name: "Shellder", type: "water", icon: "90.png" },
    { id: 91, name: "Cloyster", type: "water", icon: "91.png" },
    { id: 92, name: "Gastly", type: "ghost", icon: "92.png" },
    { id: 93, name: "Haunter", type: "ghost", icon: "93.png" },
    { id: 94, name: "Gengar", type: "ghost", icon: "94.png" },
    { id: 95, name: "Onix", type: "rock", icon: "95.png" },
    { id: 96, name: "Drowzee", type: "psychic", icon: "96.png" },
    { id: 97, name: "Hypno", type: "psychic", icon: "97.png" },
    { id: 98, name: "Krabby", type: "water", icon: "98.png" },
    { id: 99, name: "Kingler", type: "water", icon: "99.png" },
    { id: 100, name: "Voltorb", type: "electric", icon: "100.png" }
  ];
}
